import type { Locale, Problem } from './types.ts';
export const progressCopy = {
  en: {
    now: 'Where we are',
    next: 'What is still ahead',
    route: 'The ascent',
    proven: 'Demonstrated',
    unproven: 'Not established by this evidence',
    none: 'No verified AI milestone in this catalog',
    latest: 'Latest recorded result',
    history: 'Evidence trail',
    explore: 'Explore a challenge',
    all: 'All challenges',
    brief: 'Humanity’s hard problems. AI’s real progress.',
    note: 'Route positions illustrate milestones, not a completion percentage. Future goals are not forecasts.',
    reached: 'Target reached',
    limit: 'The remaining gap',
    sources: 'Read the evidence',
    selected: 'Selected challenge',
    records: 'sourced challenges',
    summary: 'Find the frontier',
    context:
      'Selected milestones, not an exhaustive account of current research.',
    choose: 'Choose a challenge to inspect its progress.',
    filter: 'Filter challenges',
    years: 'Explore over time',
    previous: 'Earlier milestone',
    date: 'Record reviewed',
  },
  'zh-CN': {
    now: '现在到了哪一步',
    next: '接下来还差什么',
    route: '攀登路线',
    proven: '已验证',
    unproven: '这些证据尚未证明',
    none: '目录中尚无已验证的 AI 里程碑',
    latest: '最近收录的结果',
    history: '证据时间线',
    explore: '探索一个难题',
    all: '全部难题',
    brief: '人类的难题，AI 的真实进展。',
    note: '路线位置仅用于呈现里程碑，不代表完成百分比。后续目标不是预测。',
    reached: '具体目标已达成',
    limit: '尚未跨越的关卡',
    sources: '查看原始证据',
    selected: '当前难题',
    records: '个有来源的难题',
    summary: '找到问题的前沿',
    context: '精选里程碑，不代表当前研究进展的完整清单。',
    choose: '选择一个问题，查看它的具体进展。',
    filter: '筛选难题',
    years: '回看历史',
    previous: '此前的里程碑',
    date: '记录核查',
  },
  es: {
    now: 'Dónde estamos',
    next: 'Qué queda por lograr',
    route: 'El ascenso',
    proven: 'Demostrado',
    unproven: 'No establecido por esta evidencia',
    none: 'Sin hitos de IA verificados en este catálogo',
    latest: 'Último resultado registrado',
    history: 'Recorrido de evidencia',
    explore: 'Explora un reto',
    all: 'Todos los retos',
    brief: 'Los retos humanos. El progreso real de la IA.',
    note: 'Las posiciones ilustran hitos, no porcentajes de avance. Los objetivos futuros no son predicciones.',
    reached: 'Objetivo alcanzado',
    limit: 'El reto pendiente',
    sources: 'Consultar la evidencia',
    selected: 'Reto seleccionado',
    records: 'retos con fuentes',
    summary: 'Encuentra la frontera',
    context:
      'Hitos seleccionados, no una descripción completa de la investigación actual.',
    choose: 'Elige un reto para examinar su progreso.',
    filter: 'Filtrar retos',
    years: 'Explorar en el tiempo',
    previous: 'Hito anterior',
    date: 'Registro revisado',
  },
} satisfies Record<Locale, Record<string, string>>;
export function routeAt(problem: Problem, year: number) {
  return problem.milestones
    .filter((m) => m.year <= year)
    .sort((a, b) => a.year - b.year);
}
