import type { Locale } from './types.ts';
export const terrainCopy = {
  en: {
    unknown: 'UNCHARTED TERRITORY',
    hint: 'Drag to orbit · Right-drag to travel · Scroll to zoom here',
    touch: 'One finger to orbit · Two fingers to travel and zoom',
    focus: 'Fly to selected peak',
    reset: 'Return to the known world',
    north: 'North',
    loading: 'Building the mountain world…',
    unavailable:
      '3D terrain is unavailable on this device. All problems, evidence and progress remain in the index below.',
    note: 'Black ranges extend beyond the mapped disciplines. They represent unknown or uncharted territory, not a count of undiscovered problems.',
    pan: 'Travel',
    orbit: 'Orbit',
    close: 'Close view',
    wide: 'Wide view',
    tilt: 'Change viewing angle',
  },
  'zh-CN': {
    unknown: '未知区域',
    hint: '拖动旋转 · 右键拖动漫游 · 滚轮缩放指向位置',
    touch: '单指旋转 · 双指移动与缩放',
    focus: '飞到选中的山峰',
    reset: '返回已知学科全景',
    north: '北',
    loading: '正在生成三维山地…',
    unavailable:
      '此设备无法显示三维地形。下方目录仍可查看所有问题、证据和进展。',
    note: '黑色山脉延伸到已知学科之外，代表未知或尚未探索的区域；不表示未知问题的实际数量。',
    pan: '漫游',
    orbit: '旋转',
    close: '近看',
    wide: '远看',
    tilt: '调整俯仰角度',
  },
  es: {
    unknown: 'TERRITORIO DESCONOCIDO',
    hint: 'Arrastra para orbitar · Botón derecho para viajar · Rueda para acercar al cursor',
    touch: 'Un dedo para orbitar · Dos dedos para mover y ampliar',
    focus: 'Volar a la cima seleccionada',
    reset: 'Volver al mundo conocido',
    north: 'Norte',
    loading: 'Generando el mundo montañoso…',
    unavailable:
      'El relieve 3D no está disponible en este dispositivo. El índice conserva todos los problemas, fuentes y avances.',
    note: 'Las cordilleras negras continúan más allá de las disciplinas cartografiadas. Representan territorio desconocido, no un recuento de problemas sin descubrir.',
    pan: 'Viajar',
    orbit: 'Orbitar',
    close: 'Acercar',
    wide: 'Alejar',
    tilt: 'Cambiar la inclinación',
  },
} satisfies Record<Locale, Record<string, string>>;
